CREATE TABLE "events" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(255) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "start_at" datetime);
CREATE TABLE "events_teams" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "event_id" integer NOT NULL, "team_id" integer NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "game_groups" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "event_id" integer NOT NULL, "title" varchar(255) NOT NULL, "pos" integer NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "calc" boolean DEFAULT 'f');
CREATE TABLE "games" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "game_group_id" integer NOT NULL, "pos" integer NOT NULL, "team1_id" integer NOT NULL, "team2_id" integer NOT NULL, "play_at" datetime NOT NULL, "score1" integer, "score2" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "knockout" boolean DEFAULT 'f', "score3" integer, "score4" integer, "score5" integer, "score6" integer);
CREATE TABLE "pools" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "event_id" integer NOT NULL, "title" varchar(255) NOT NULL, "user_id" integer NOT NULL, "welcome" text, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "fix" boolean DEFAULT 'f');
CREATE TABLE "pools_users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "pool_id" integer NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "team1_id" integer, "team2_id" integer, "team3_id" integer, "points" integer);
CREATE TABLE "schema_migrations" ("version" varchar(255) NOT NULL);
CREATE TABLE "teams" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "title" varchar(255) NOT NULL, "img" varchar(255), "calc" boolean DEFAULT 'f' NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE TABLE "tips" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "user_id" integer NOT NULL, "pool_id" integer NOT NULL, "game_id" integer NOT NULL, "score1" integer, "score2" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "score3" integer, "score4" integer, "score5" integer, "score6" integer);
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255) NOT NULL, "email" varchar(255), "password" varchar(255), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
INSERT INTO schema_migrations (version) VALUES ('20120305214015');

INSERT INTO schema_migrations (version) VALUES ('20120312165907');